spring:
  datasource:
    url: mpw:I/8l8v72Vp59soQae3dflDI7rKIM5VpBbAP3ENXCyddzV7VgvjEFX0JZK2x+uvFSxju2muCV6nyxnHLjywlCkAWIyhLqrWnCWWrrcKulYok=
    username: mpw:gyd3tdZJgfMVRcP4Nh8abA==
    password: mpw:zPwjddIt8Fe+ii9GZZVIlg==
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 60000
      max-lifetime: 180000
      connection-timeout: 3000
      pool-name: passwordManagerPool
  data:
    redis:
      password: d0isSRu4iWtDyOj
      host: 172.31.61.167
      port: 6379
      username: HomeSkating
mybatis-plus:
  global-config:
    db-config:
      id-type: assign_id
      table-prefix: "yq_pm_"
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8848
  http2:
    enabled: true
logging:
  level:
    org.springframework.security: DEBUG

