spring:
  datasource:
    url: jdbc:mysql://192.168.205.128:3306/yq_password_manager
    username: yiquangu
    password: x)4al2[W&@6Ido=
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      password: d0isSRu4iWtDyOj
  security:
    user:
      name: yiquangu
      password: mh3EZDDhRs4agkC
mybatis-plus:
  global-config:
    db-config:
      id-type: assign_id
  configuration:
    map-underscore-to-camel-case: true

