spring:
  datasource:
    url: mpw:I/8l8v72Vp59soQae3dflDI7rKIM5VpBbAP3ENXCyddzV7VgvjEFX0JZK2x+uvFSfUj4nfFSMDgdoNxRhOWmUDBUP9hQBjHQQVWn9IFOM1Gp84mKs4ueBuAveor121TNG9LhQIeawNMJ1zUZxm1gVNtpNnl8ul1Q76fDmEHJZAU=
    username: mpw:TB524VPh/1y1K7Gj07LVTw==
    password: mpw:zPwjddIt8Fe+ii9GZZVIlg==
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      password: d0isSRu4iWtDyOj
      host: 192.168.205.128
      port: 6379
      username: homeskating
  security:
    user:
      name: yiquangu
      password: mh3EZDDhRs4agkC
mybatis-plus:
  global-config:
    db-config:
      id-type: assign_id
  configuration:
    map-underscore-to-camel-case: true

